name: Update Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution graph
        uses: pipipi-dev/gcchart@v1
        with:
          outputs: |
            contributions.svg
